NAME = phone

SRC = MyAwesomePhonebook.cpp

FLAGS = -Wall -Werror -Wextra

CPP_V = -std=c++98

${NAME} :
	@printf "\n"
	@printf "Creating your awesome phonebook ! : \n"
	c++ ${CPP_v} ${FLAGS} ${SRC} -o ${NAME}
	@printf "\n"

all : ${NAME}

clean :
	rm -rf ${NAME}

re :	clean all

.PHONY: all clean re
